version: "3.7"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/tmp/redis.conf
    command: [ "redis-server", "/tmp/redis.conf"]
    networks:
      - redis-net

  testing-app:
    container_name: testing_app
    depends_on:
      - redis
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge